### PR TITLE
Updated requirements.txt to patch django bug

### PR DESCRIPTION
**Pull request by DrWhax**
Patches: https://github.com/advisories/GHSA-vfq6-hq5r-27r6

### CODE REVIEW

**Comment by stas** [comment]
Thanks @DrWhax!

A larger plan to move away from Python2 is on it's way btw.

**Comment by DrWhax** [comment]
Thx for merging! :)

PY3 version sounds great!

**Comment by pudo** [comment]
I tried upgrading Django on this before, I'm pretty sure master is now broken.

**Comment by stas** [comment]
I'll take a look, travis says it's all green lol

**Pull request merged**
